const questions = [
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0002.mp3',
    rightAnswer: 'alkogol',
    english: 'alcohol',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0002.jpg',
    options: [
      'xleb',
      'alkogol',
      'morojennoe',
      'kepka',
      'pirog',
      'zaryadka',
    ],
  },
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0003.mp3',
    rightAnswer: 'priyti',
    english: 'arrive',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0003.jpg',
    options: [
      'priyti',
      'uyti',
      'polzti',
      'nesti',
      'delat',
      'bejat',
    ],
  },
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0004.mp3',
    rightAnswer: 'avgust',
    english: 'august',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0004.jpg',
    options: [
      'sentabr',
      'oktabr',
      'yanvar',
      'avgust',
      'fevral',
      'mart',
    ],
  },
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0005.mp3',
    rightAnswer: 'lodka',
    english: 'boat',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0005.jpg',
    options: [
      'kayuta',
      'ruchka',
      'bakalashka',
      'telefon',
      'lodka',
      'kepka',
    ],
  },
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0006.mp3',
    rightAnswer: 'zavtrak',
    english: 'breakfast',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0006.jpg',
    options: [
      'obed',
      'ujin',
      'zavtrak',
      'tetrad',
      'poldnik',
      'divan',
    ],
  },
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0007.mp3',
    rightAnswer: 'kamera',
    english: 'camera',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0007.jpg',
    options: [
      'televizor',
      'telefon',
      'kamera',
      'zaryadka',
      'vishnya',
      'listok',
    ],
  },
  {
    question: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0008.mp3',
    rightAnswer: 'stolica',
    english: 'capital',
    image: 'https://raw.githubusercontent.com/ulmas97/rslang-data/master/data/01_0008.jpg',
    options: [
      'gorod',
      'obast',
      'strana',
      'kishlak',
      'stolica',
      'shtat',
    ],
  },
];
export default questions;
